### ISSUE TITLE
Travis broken for 7, 7.4, 7.6 (cabal issue)

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/th-reify-many#8]
See https://travis-ci.org/mgsloan/th-reify-many/builds/242267859 (seems to be unrelated to the actual change there)

```
cabal: Error: some packages failed to install:
safe-0.3.11 failed during the configure step. The exception was:
user error (The package 'safe' requires Cabal library version -any && >=1.18
but no suitable version is installed.)
```

Not sure how to solve this, as clearly 1.18 is installed.  Going to allow these environments to fail for now, as I don't have time to futz around with cabal-install.  Could consider dropping support for GHC < 7.8, that'd be reasonable at this point.

**Comment by RyanGlScott** [comment]
This is due to https://github.com/haskell/cabal/issues/4624. I've ran into this issue myself - for the time being, I've bumped all of my `cabal-install` versions to at least 2.0 as a workaround (see https://github.com/ekmett/semigroupoids/commit/ef085d1cbe4a04245c5ace8be63e6de0c7151dcd).

**Comment by RyanGlScott** [comment]
The problem [should be fixed now](https://github.com/haskell/cabal/issues/4624#issuecomment-318743713).

**Comment by mgsloan** [comment]
@RyanGlScott Thanks for letting me know!  Unfortunately seems to still fail - https://travis-ci.org/mgsloan/th-reify-many/builds/259180197?utm_source=email&utm_medium=notification hmm

**Comment by RyanGlScott** [comment]
This is due to a separate bug in old versions of `Cabal`, funny enough. I've also encountered it in places like https://github.com/goldfirere/th-desugar/pull/46#discussion_r91593073.

The workaround is to use `Cabal-1.24` or later, which doesn't appear to suffer from this problem.

**Comment by hvr** [comment]
You may want to give `cabal new-test` a try here (e.g. via https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs):

```
$ cabal new-test -w ghc-7.6.3
Resolving dependencies...
Build profile: -w ghc-7.6.3 -O1
In order, the following will be built (use -v for more details):
 - th-expand-syns-0.4.3.0 {th-expand-syns-0.4.3.0-7e8190c252eec48679c80adfac60a1a84e22f9ebf6eeb43449db2e3ffd5b890c} (lib) (requires build)
 - th-reify-many-0.1.8 {th-reify-many-0.1.8-inplace} (lib) (first run)
 - th-reify-many-0.1.8 {th-reify-many-0.1.8-inplace-test} (test:test) (first run)
Configuring  th-expand-syns-0.4.3.0-7e8190c252eec48679c80adfac60a1a84e22f9ebf6eeb43449db2e3ffd5b890c (lib)
Building     th-expand-syns-0.4.3.0-7e8190c252eec48679c80adfac60a1a84e22f9ebf6eeb43449db2e3ffd5b890c (lib)
Installing   th-expand-syns-0.4.3.0-7e8190c252eec48679c80adfac60a1a84e22f9ebf6eeb43449db2e3ffd5b890c (lib)
Finished     th-expand-syns-0.4.3.0-7e8190c252eec48679c80adfac60a1a84e22f9ebf6eeb43449db2e3ffd5b890c (lib)
Configuring library for th-reify-many-0.1.8..
Preprocessing library for th-reify-many-0.1.8..
Building library for th-reify-many-0.1.8..
[1 of 2] Compiling Language.Haskell.TH.ReifyMany.Internal ( src/Language/Haskell/TH/ReifyMany/Internal.hs, /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.6.3/th-reify-many-0.1.8/build/Language/Haskell/TH/ReifyMany/Internal.o )
[2 of 2] Compiling Language.Haskell.TH.ReifyMany ( src/Language/Haskell/TH/ReifyMany.hs, /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.6.3/th-reify-many-0.1.8/build/Language/Haskell/TH/ReifyMany.o )
Configuring test suite 'test' for th-reify-many-0.1.8..
Preprocessing test suite 'test' for th-reify-many-0.1.8..
Building test suite 'test' for th-reify-many-0.1.8..
[1 of 1] Compiling Main             ( tests/Main.hs, /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.6.3/th-reify-many-0.1.8/c/test/build/test/test-tmp/Main.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package containers-0.5.0.0 ... linking ... done.
Loading package transformers-0.5.4.0 ... linking ... done.
Loading package mtl-2.2.1 ... linking ... done.
Loading package safe-0.3.15 ... linking ... done.
Loading package pretty-1.1.1.0 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package syb-0.7 ... linking ... done.
Loading package th-expand-syns-0.4.3.0 ... linking ... done.
Loading package th-reify-many-0.1.8 ... linking ... done.
Linking /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.6.3/th-reify-many-0.1.8/c/test/build/test/test ...
Running 1 test suites...
Test suite test: RUNNING...
worked!
Test suite test: PASS
Test suite logged to:
/tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.6.3/th-reify-many-0.1.8/c/test/test/th-reify-many-0.1.8-test.log
1 of 1 test suites (1 of 1 test cases) passed.
```


```
$ cabal new-test -w ghc-7.0.4
Resolving dependencies...
Build profile: -w ghc-7.0.4 -O1
In order, the following will be built (use -v for more details):
 - th-expand-syns-0.4.3.0 {th-expand-syns-0.4.3.0-743952279825283b077fd7e531cac0f2ee54197e52521a3a0885f99fbce566ea} (lib) (requires build)
 - th-reify-many-0.1.8 {th-reify-many-0.1.8-inplace} (lib) (first run)
 - th-reify-many-0.1.8 {th-reify-many-0.1.8-inplace-test} (test:test) (first run)
Configuring  th-expand-syns-0.4.3.0-743952279825283b077fd7e531cac0f2ee54197e52521a3a0885f99fbce566ea (lib)
Building     th-expand-syns-0.4.3.0-743952279825283b077fd7e531cac0f2ee54197e52521a3a0885f99fbce566ea (lib)
Installing   th-expand-syns-0.4.3.0-743952279825283b077fd7e531cac0f2ee54197e52521a3a0885f99fbce566ea (lib)
Finished     th-expand-syns-0.4.3.0-743952279825283b077fd7e531cac0f2ee54197e52521a3a0885f99fbce566ea (lib)
Configuring library for th-reify-many-0.1.8..
Preprocessing library for th-reify-many-0.1.8..
Building library for th-reify-many-0.1.8..
[1 of 2] Compiling Language.Haskell.TH.ReifyMany.Internal ( src/Language/Haskell/TH/ReifyMany/Internal.hs, /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.0.4/th-reify-many-0.1.8/build/Language/Haskell/TH/ReifyMany/Internal.o )
[2 of 2] Compiling Language.Haskell.TH.ReifyMany ( src/Language/Haskell/TH/ReifyMany.hs, /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.0.4/th-reify-many-0.1.8/build/Language/Haskell/TH/ReifyMany.o )
Configuring test suite 'test' for th-reify-many-0.1.8..
Preprocessing test suite 'test' for th-reify-many-0.1.8..
Building test suite 'test' for th-reify-many-0.1.8..
[1 of 1] Compiling Main             ( tests/Main.hs, /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.0.4/th-reify-many-0.1.8/c/test/build/test/test-tmp/Main.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.3.0.2 ... linking ... done.
Loading package containers-0.4.0.0 ... linking ... done.
Loading package transformers-0.5.4.0 ... linking ... done.
Loading package mtl-2.2.1 ... linking ... done.
Loading package safe-0.3.11 ... linking ... done.
Loading package pretty-1.0.1.2 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package syb-0.7 ... linking ... done.
Loading package th-expand-syns-0.4.3.0 ... linking ... done.
Loading package th-reify-many-0.1.8 ... linking ... done.
Loading package ffi-1.0 ... linking ... done.
Linking /tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.0.4/th-reify-many-0.1.8/c/test/build/test/test ...
Running 1 test suites...
Test suite test: RUNNING...
worked!
Test suite test: PASS
Test suite logged to:
/tmp/th-reify-many/dist-newstyle/build/x86_64-linux/ghc-7.0.4/th-reify-many-0.1.8/c/test/test/th-reify-many-0.1.8-test.log
1 of 1 test suites (1 of 1 test cases) passed.
```

**Comment by RyanGlScott** [comment]
This should be fixed as of cfff979, which uses `cabal v2-`style builds in the CI.
